# Generated by Django 6.0.5 on 2026-05-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(max_length=100)),
                ('crop_name_hi', models.CharField(blank=True, max_length=100)),
                ('mandi_name', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(default='Quintal', max_length=20)),
                ('date', models.DateField()),
                ('trend', models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('stable', 'Stable')], default='stable', max_length=10)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
