# Generated by Django 6.0.5 on 2026-05-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ne',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='name_ne',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
